"""baseline schema

Revision ID: ba62bae580d4
Revises: 
Create Date: 2026-09-12 19:39:10.590856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba62bae580d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotation_target', 'annotations', ['target_type', 'target_key'], unique=False)
    op.create_table('app_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_key', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('flag_name', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_target', 'audit_events', ['target_type', 'target_key'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), server_default='object', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingest_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_jobs_status'), 'ingest_jobs', ['status'], unique=False)
    op.create_table('metadata_dbs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filesize', sa.String(), nullable=True),
    sa.Column('last_file_update', sa.DateTime(), nullable=True),
    sa.Column('date_ingested', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpc_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('designation')
    )
    op.create_table('results_dbs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filesize', sa.BigInteger(), nullable=True),
    sa.Column('last_file_update', sa.DateTime(), nullable=True),
    sa.Column('date_ingested', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_dbs_natural_key'), 'results_dbs', ['natural_key'], unique=True)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entity_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_key', sa.String(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('attached', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_key', 'flag_id', name='uq_entity_flag')
    )
    op.create_index('ix_entity_flag_target', 'entity_flag', ['target_type', 'target_key'], unique=False)
    op.create_table('mpc_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mpc_candidate_id', sa.Integer(), nullable=False),
    sa.Column('trksub', sa.String(), nullable=False),
    sa.Column('iau_desig', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('datetime_ut', sa.String(), nullable=True),
    sa.Column('desig_page', sa.String(), nullable=True),
    sa.Column('reference_page', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mpc_candidate_id'], ['mpc_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpc_candidate_id', name='uq_candidate')
    )
    op.create_table('object_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('attached', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key', 'flag_id', name='uq_obj_flag')
    )
    op.create_index(op.f('ix_object_flag_object_key'), 'object_flag', ['object_key'], unique=False)
    op.create_table('observation_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_key', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('attached', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_key', 'tag_id', name='uq_obs_tag')
    )
    op.create_index(op.f('ix_observation_tag_observation_key'), 'observation_tag', ['observation_key'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metadata_db_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('acq_system_id', sa.Integer(), nullable=False),
    sa.Column('acq_timestamp', sa.Integer(), nullable=False),
    sa.Column('acq_num_1', sa.Integer(), nullable=False),
    sa.Column('acq_num_2', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sequence_len', sa.Integer(), nullable=False),
    sa.Column('obstime', sa.DateTime(), nullable=True),
    sa.Column('rowid', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_calib', sa.Boolean(), nullable=True),
    sa.Column('is_science', sa.Boolean(), nullable=True),
    sa.Column('is_bias', sa.Boolean(), nullable=True),
    sa.Column('is_dark', sa.Boolean(), nullable=True),
    sa.Column('is_flat', sa.Boolean(), nullable=True),
    sa.Column('exptime', sa.Float(), nullable=True),
    sa.Column('frames', sa.Integer(), nullable=True),
    sa.Column('filter', sa.String(), nullable=True),
    sa.Column('tele_ra', sa.Float(), nullable=True),
    sa.Column('tele_dec', sa.Float(), nullable=True),
    sa.Column('camera_name', sa.String(), nullable=True),
    sa.Column('gain', sa.Float(), nullable=True),
    sa.Column('binning_mode', sa.String(), nullable=True),
    sa.Column('operation_mode', sa.String(), nullable=True),
    sa.Column('binning_size', sa.Integer(), nullable=True),
    sa.Column('roi_start_x', sa.Integer(), nullable=True),
    sa.Column('roi_start_y', sa.Integer(), nullable=True),
    sa.Column('roi_width', sa.Integer(), nullable=True),
    sa.Column('roi_height', sa.Integer(), nullable=True),
    sa.Column('cooler_on', sa.Boolean(), nullable=True),
    sa.Column('target_temp', sa.Float(), nullable=True),
    sa.Column('front_housing_temp', sa.Float(), nullable=True),
    sa.Column('rear_housing_temp', sa.Float(), nullable=True),
    sa.Column('camera_temp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_db_id'], ['metadata_dbs.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acq_system_id', 'acq_timestamp', 'acq_num_1', 'acq_num_2', name='uq_dataset_natural')
    )
    op.create_index(op.f('ix_observations_natural_key'), 'observations', ['natural_key'], unique=True)
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_description', sa.String(), nullable=True),
    sa.Column('analysis_time', sa.DateTime(), nullable=False),
    sa.Column('obs_time', sa.DateTime(), nullable=False),
    sa.Column('sky_mag', sa.Float(), nullable=True),
    sa.Column('detection_limit_mag', sa.Float(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results_db_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('n_objects', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['results_db_id'], ['results_dbs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('results_db_id', 'analysis_id', name='uq_run_natural')
    )
    op.create_index(op.f('ix_analysis_runs_natural_key'), 'analysis_runs', ['natural_key'], unique=True)
    op.create_table('fits_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpc_encounters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('mpc_candidate_id', sa.Integer(), nullable=False),
    sa.Column('d_ra', sa.Float(), nullable=False),
    sa.Column('d_dec', sa.Float(), nullable=False),
    sa.Column('v_mag', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mpc_candidate_id'], ['mpc_candidates.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blob_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(), nullable=False),
    sa.Column('image_type', sa.Integer(), nullable=True),
    sa.Column('image_index', sa.Integer(), nullable=True),
    sa.Column('source_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.String(), nullable=False),
    sa.Column('size_class', sa.String(), nullable=False),
    sa.Column('vmin', sa.Float(), nullable=True),
    sa.Column('vmax', sa.Float(), nullable=True),
    sa.Column('percentiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('histogram', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('thumbnail_png_path', sa.String(), nullable=True),
    sa.Column('nan_present', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'source_table', 'image_type', 'image_index', name='uq_blob_natural')
    )
    op.create_index(op.f('ix_blob_ref_natural_key'), 'blob_ref', ['natural_key'], unique=True)
    op.create_table('detected_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('object_index', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('blob_ref_id', sa.Integer(), nullable=True),
    sa.Column('snr', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('num_frames', sa.Integer(), nullable=False),
    sa.Column('cluster_children', sa.Integer(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('v_ra', sa.Float(), nullable=True),
    sa.Column('v_dec', sa.Float(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('vx', sa.Float(), nullable=True),
    sa.Column('vy', sa.Float(), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('source_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_time', sa.DateTime(), nullable=False),
    sa.Column('obs_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['blob_ref_id'], ['blob_ref.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'object_index', name='uq_object_natural')
    )
    op.create_index(op.f('ix_detected_objects_natural_key'), 'detected_objects', ['natural_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detected_objects_natural_key'), table_name='detected_objects')
    op.drop_table('detected_objects')
    op.drop_index(op.f('ix_blob_ref_natural_key'), table_name='blob_ref')
    op.drop_table('blob_ref')
    op.drop_table('mpc_encounters')
    op.drop_table('fits_files')
    op.drop_index(op.f('ix_analysis_runs_natural_key'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_observations_natural_key'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_observation_tag_observation_key'), table_name='observation_tag')
    op.drop_table('observation_tag')
    op.drop_index(op.f('ix_object_flag_object_key'), table_name='object_flag')
    op.drop_table('object_flag')
    op.drop_table('mpc_status')
    op.drop_index('ix_entity_flag_target', table_name='entity_flag')
    op.drop_table('entity_flag')
    op.drop_table('tags')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_results_dbs_natural_key'), table_name='results_dbs')
    op.drop_table('results_dbs')
    op.drop_table('mpc_candidates')
    op.drop_table('metadata_dbs')
    op.drop_index(op.f('ix_ingest_jobs_status'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_table('flags')
    op.drop_index('ix_audit_target', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('app_config')
    op.drop_index('ix_annotation_target', table_name='annotations')
    op.drop_table('annotations')
    # ### end Alembic commands ###
